"""add step for task

Revision ID: bc6c239fd66a
Revises: bfeced16c794
Create Date: 2025-12-18 20:53:58.009168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6c239fd66a'
down_revision: Union[str, None] = 'bfeced16c794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) add columns as nullable to allow backfill
    op.add_column('task_executions', sa.Column('step', sa.Integer(), nullable=True))
    op.add_column('task_executions', sa.Column('total_steps', sa.Integer(), nullable=True))
    # 2) backfill existing rows to 1/1
    op.execute("UPDATE task_executions SET step = 1 WHERE step IS NULL")
    op.execute("UPDATE task_executions SET total_steps = 1 WHERE total_steps IS NULL")
    # 3) enforce not-null
    op.alter_column('task_executions', 'step', nullable=False)
    op.alter_column('task_executions', 'total_steps', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_executions', 'total_steps')
    op.drop_column('task_executions', 'step')
    # ### end Alembic commands ###
