"""Add agent fields to AICall model

Revision ID: f3f7e258fb3a
Revises: b66996638246
Create Date: 2025-12-08 12:43:10.154854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3f7e258fb3a'
down_revision: Union[str, None] = 'b66996638246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_calls', sa.Column('agent_id', sa.String(length=100), nullable=True))
    op.add_column('ai_calls', sa.Column('agent_version', sa.String(length=50), nullable=True))
    op.add_column('ai_calls', sa.Column('requests', sa.Integer(), nullable=True))
    op.add_column('ai_calls', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.alter_column('ai_calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_calls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_ai_calls_task'), table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_user'), table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_workflow'), table_name='ai_calls')
    op.create_index(op.f('ix_ai_calls_task_id'), 'ai_calls', ['task_id'], unique=False)
    op.create_index(op.f('ix_ai_calls_user_id'), 'ai_calls', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_calls_workflow_id'), 'ai_calls', ['workflow_id'], unique=False)
    op.drop_column('ai_calls', 'prompt_version')
    op.drop_column('ai_calls', 'prompt_id')
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('PENDING', 'TAILORING', 'READY', 'APPLIED', 'PHONE_SCREEN', 'INTERVIEWING', 'OFFER', 'REJECTED', 'FAILED', name='applicationstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"))
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_applications_cover_letter_doc'), table_name='applications')
    op.drop_index(op.f('ix_applications_deleted'), table_name='applications')
    op.drop_index(op.f('ix_applications_resume_doc'), table_name='applications')
    op.drop_index(op.f('ix_applications_user_job'), table_name='applications')
    op.create_index(op.f('ix_applications_is_deleted'), 'applications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_unique_constraint('uq_applications_user_job', 'applications', ['user_id', 'job_id'])
    op.alter_column('documents', 'format',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MARKDOWN', 'HTML', 'PLAINTEXT', name='documentformat', native_enum=False),
               existing_nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('job_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('job_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('job_analyses_job_id_unique'), 'job_analyses', type_='unique')
    op.drop_index(op.f('ix_job_analyses_job_id'), table_name='job_analyses')
    op.create_index(op.f('ix_job_analyses_job_id'), 'job_analyses', ['job_id'], unique=True)
    op.alter_column('outbox_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('outbox_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_outbox_aggregate'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_unpublished'), table_name='outbox_events')
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_published'), 'outbox_events', ['published'], unique=False)
    op.alter_column('resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resumes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('task_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('task_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_task_name'), table_name='task_executions')
    op.drop_index(op.f('ix_task_workflow_status'), table_name='task_executions')
    op.create_index(op.f('ix_task_executions_workflow_id'), 'task_executions', ['workflow_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('workflow_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('workflow_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_workflow_type_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_user_status'), table_name='workflow_executions')
    op.create_index(op.f('ix_workflow_executions_entity_id'), 'workflow_executions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_user_id'), 'workflow_executions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_executions_user_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_entity_id'), table_name='workflow_executions')
    op.create_index(op.f('ix_workflow_user_status'), 'workflow_executions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_type_status'), 'workflow_executions', ['workflow_type', 'status'], unique=False)
    op.alter_column('workflow_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('workflow_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_task_executions_workflow_id'), table_name='task_executions')
    op.create_index(op.f('ix_task_workflow_status'), 'task_executions', ['workflow_id', 'status'], unique=False)
    op.create_index(op.f('ix_task_name'), 'task_executions', ['task_name'], unique=False)
    op.alter_column('task_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('task_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resumes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_outbox_events_published'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.create_index(op.f('ix_outbox_unpublished'), 'outbox_events', ['published', 'created_at'], unique=False)
    op.create_index(op.f('ix_outbox_aggregate'), 'outbox_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.alter_column('outbox_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('outbox_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_job_analyses_job_id'), table_name='job_analyses')
    op.create_index(op.f('ix_job_analyses_job_id'), 'job_analyses', ['job_id'], unique=False)
    op.create_unique_constraint(op.f('job_analyses_job_id_unique'), 'job_analyses', ['job_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('job_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('job_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'format',
               existing_type=sa.Enum('MARKDOWN', 'HTML', 'PLAINTEXT', name='documentformat', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint('uq_applications_user_job', 'applications', type_='unique')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_is_deleted'), table_name='applications')
    op.create_index(op.f('ix_applications_user_job'), 'applications', ['user_id', 'job_id'], unique=True)
    op.create_index(op.f('ix_applications_resume_doc'), 'applications', ['resume_document_id'], unique=False)
    op.create_index(op.f('ix_applications_deleted'), 'applications', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_applications_cover_letter_doc'), 'applications', ['cover_letter_document_id'], unique=False)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('PENDING', 'TAILORING', 'READY', 'APPLIED', 'PHONE_SCREEN', 'INTERVIEWING', 'OFFER', 'REJECTED', 'FAILED', name='applicationstatus', native_enum=False),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"))
    op.add_column('ai_calls', sa.Column('prompt_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_calls', sa.Column('prompt_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ai_calls_workflow_id'), table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_user_id'), table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_task_id'), table_name='ai_calls')
    op.create_index(op.f('ix_ai_calls_workflow'), 'ai_calls', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_ai_calls_user'), 'ai_calls', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_calls_task'), 'ai_calls', ['task_id'], unique=False)
    op.alter_column('ai_calls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('ai_calls', 'estimated_cost')
    op.drop_column('ai_calls', 'requests')
    op.drop_column('ai_calls', 'agent_version')
    op.drop_column('ai_calls', 'agent_id')
    # ### end Alembic commands ###
