"""Add needs_reanalysis to job_analyses

Revision ID: 0747b17e4371
Revises: f3f7e258fb3a
Create Date: 2025-12-08 18:17:45.513649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0747b17e4371'
down_revision: Union[str, None] = 'f3f7e258fb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_analyses', sa.Column('needs_reanalysis', sa.Boolean(), nullable=False, server_default='false', comment='Flag to trigger re-analysis'))
    op.create_index(op.f('ix_job_analyses_needs_reanalysis'), 'job_analyses', ['needs_reanalysis'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_analyses_needs_reanalysis'), table_name='job_analyses')
    op.drop_column('job_analyses', 'needs_reanalysis')
    # ### end Alembic commands ###
