"""add tailoring_progress

Revision ID: 58029218abb0
Revises: b1d0f0a12345
Create Date: 2025-12-16 16:56:24.313152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58029218abb0'
down_revision: Union[str, None] = 'b1d0f0a12345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('tailoring_progress', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'tailoring_progress')
    # ### end Alembic commands ###
