"""aicall

Revision ID: 5ad4fc7e9426
Revises: b6a3d58b1436
Create Date: 2025-12-19 19:48:29.418367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad4fc7e9426'
down_revision: Union[str, None] = 'b6a3d58b1436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_calls', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ai_calls', 'agent_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ai_calls', 'agent_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(op.f('ai_calls_user_id_fkey'), 'ai_calls', type_='foreignkey')
    op.create_foreign_key(None, 'ai_calls', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_calls', type_='foreignkey')
    op.create_foreign_key(op.f('ai_calls_user_id_fkey'), 'ai_calls', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ai_calls', 'agent_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ai_calls', 'agent_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ai_calls', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
