"""add cn_content

Revision ID: bfeced16c794
Revises: 58029218abb0
Create Date: 2025-12-17 12:35:50.678694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfeced16c794'
down_revision: Union[str, None] = '58029218abb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_analyses', sa.Column('cn_content', sa.Text(), nullable=True, comment='Translated job description in Chinese'))
    op.create_index(op.f('ix_task_executions_user_id'), 'task_executions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_executions_user_id'), table_name='task_executions')
    op.drop_column('job_analyses', 'cn_content')
    # ### end Alembic commands ###
