"""add job user match

Revision ID: eae6f0c6b418
Revises: add_resume_analysis_user_skills
Create Date: 2025-12-10 11:11:16.724773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eae6f0c6b418'
down_revision: Union[str, None] = 'add_resume_analysis_user_skills'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_job_matches',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_match_score', sa.Float(), nullable=False),
    sa.Column('skill_match_details', sa.JSON(), nullable=False),
    sa.Column('recommended_resume_id', sa.String(length=255), nullable=True),
    sa.Column('resume_match_score', sa.Float(), nullable=True),
    sa.Column('resume_match_details', sa.JSON(), nullable=True),
    sa.Column('ai_match_score', sa.Float(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('matching_algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['job_id'], ['seek_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job_match')
    )
    op.create_index(op.f('ix_user_job_matches_ai_analyzed_at'), 'user_job_matches', ['ai_analyzed_at'], unique=False)
    op.create_index(op.f('ix_user_job_matches_calculated_at'), 'user_job_matches', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_user_job_matches_job_id'), 'user_job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_user_job_matches_user_id'), 'user_job_matches', ['user_id'], unique=False)
    op.add_column('job_analyses', sa.Column('normalized_job_title', sa.String(length=150), nullable=True, comment="Standardized job title (e.g., 'Backend Developer')"))
    op.alter_column('job_analyses', 'seniority',
               existing_type=sa.VARCHAR(length=50),
               comment='Seniority level (Junior, Intermediate, Senior, Lead)',
               existing_comment='Seniority level (Junior, Mid, Senior, Lead)',
               existing_nullable=True)
    op.create_index(op.f('ix_job_analyses_normalized_job_title'), 'job_analyses', ['normalized_job_title'], unique=False)
    op.add_column('resumes', sa.Column('target_job_titles', sa.JSON(), nullable=True, comment='Top recommended job titles from resume analysis (3-5 items)'))
    op.alter_column('user_skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_user_skills_user_skill_type'), table_name='user_skills')
    op.drop_constraint(op.f('uq_user_skills_user_skill'), 'user_skills', type_='unique')
    op.alter_column('workflow_executions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_executions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_user_skills_user_skill'), 'user_skills', ['user_id', 'skill_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_skills_user_skill_type'), 'user_skills', ['user_id', 'skill_type'], unique=False)
    op.alter_column('user_skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('resumes', 'target_job_titles')
    op.drop_index(op.f('ix_job_analyses_normalized_job_title'), table_name='job_analyses')
    op.alter_column('job_analyses', 'seniority',
               existing_type=sa.VARCHAR(length=50),
               comment='Seniority level (Junior, Mid, Senior, Lead)',
               existing_comment='Seniority level (Junior, Intermediate, Senior, Lead)',
               existing_nullable=True)
    op.drop_column('job_analyses', 'normalized_job_title')
    op.drop_index(op.f('ix_user_job_matches_user_id'), table_name='user_job_matches')
    op.drop_index(op.f('ix_user_job_matches_job_id'), table_name='user_job_matches')
    op.drop_index(op.f('ix_user_job_matches_calculated_at'), table_name='user_job_matches')
    op.drop_index(op.f('ix_user_job_matches_ai_analyzed_at'), table_name='user_job_matches')
    op.drop_table('user_job_matches')
    # ### end Alembic commands ###
