"""refactor user skills

Revision ID: b6a3d58b1436
Revises: bc6c239fd66a
Create Date: 2025-12-18 22:47:21.658110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6a3d58b1436'
down_revision: Union[str, None] = 'bc6c239fd66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_skills',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.String(length=255), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel', native_enum=False), nullable=False),
    sa.Column('extracted_from', sa.JSON(), nullable=True, comment='Optional: which section this skill was extracted from'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'skill_name', name='uk_resume_skill')
    )
    op.create_index('idx_resume_skills_resume', 'resume_skills', ['resume_id'], unique=False)
    op.create_index('idx_resume_skills_user', 'resume_skills', ['user_id', 'skill_name'], unique=False)
    op.create_index(op.f('ix_resume_skills_resume_id'), 'resume_skills', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_skills_user_id'), 'resume_skills', ['user_id'], unique=False)
    op.drop_table('user_skills')
    op.create_table('user_skills',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel', native_enum=False), nullable=False),
    sa.Column('is_manual', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether manually edited by user'),
    sa.Column('manual_proficiency', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiencylevel', native_enum=False), nullable=True, comment='User-set proficiency if manually edited'),
    sa.Column('source_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='How many resumes mention this skill'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='Last time this skill appeared in a resume'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_name', name='uk_user_skill')
    )
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_index('idx_user_skills_manual', 'user_skills', ['user_id', 'is_manual'], unique=False)
    op.create_index('idx_user_skills_proficiency', 'user_skills', ['user_id', 'proficiency_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_skills_proficiency', table_name='user_skills')
    op.drop_index('idx_user_skills_manual', table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_table('user_skills')
    op.create_table('user_skills',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=200), nullable=False),
    sa.Column('proficiency', sa.VARCHAR(length=20), nullable=False),
    sa.Column('skill_type', sa.VARCHAR(length=50), server_default=sa.text("'technical'::character varying"), nullable=False),
    sa.Column('extracted_from_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_name', name='uq_user_skills_user_skill')
    )
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_index('ix_user_skills_user_skill_type', 'user_skills', ['user_id', 'skill_type'], unique=False)
    op.drop_index(op.f('ix_resume_skills_user_id'), table_name='resume_skills')
    op.drop_index(op.f('ix_resume_skills_resume_id'), table_name='resume_skills')
    op.drop_index('idx_resume_skills_user', table_name='resume_skills')
    op.drop_index('idx_resume_skills_resume', table_name='resume_skills')
    op.drop_table('resume_skills')
    # ### end Alembic commands ###
